#ifndef __CONFIG_H__
#define __CONFIG_H__
#define CONFIG_CPU_ARM y
#define CONFIG_CPU_ARMV7 y
#define CONFIG_CPU_ARM_THUMB y
#define CONFIG_CPU_ARMV7M y
#define CONFIG_CPU_ARM_CORTEX_M4 y
#define CONFIG_LITTLE_ENDIAN y
#define CONFIG_STACK_SIZE 0x800
#define CONFIG_NUM_IRQS 61
#define CONFIG_NVIC_PRIO_BITS 4
#define CONFIG_MAX_THREADS 5
#define CONFIG_THREAD_STACK_START 0x20008000
#define CONFIG_THREAD_STACK_SIZE 0x800
#define CONFIG_SCHEDULE_PRIORITY y
#define CONFIG_SEMAPHORE y
#define CONFIG_MUTEX y
#define CONFIG_TEXT_BASE 0x8000000
#define CONFIG_TEXT_SIZE 0xFFFF
#define CONFIG_RAM_BASE 0x20000000
#define CONFIG_RAM_SIZE 0xFFFF
#define CONFIG_USART_DEBUG y
#endif /* __CONFIG_H__ */
