obj-$(CONFIG_MUTEX) := kmutex.o
obj-y += scheduler.o
obj-$(CONFIG_SEMAPHORE) += ksem.o
obj-$(CONFIG_SYSCALL) += syscall.o
obj-$(CONFIG_QUEUE) += kqueue.o
obj-y += thread.o
obj-y += ktime.o
obj-y += wait.o
