obj-y += utils.o
obj-$(CONFIG_TRACE) += SEGGER_SYSVIEW.o
obj-$(CONFIG_TRACE) += SEGGER_SYSVIEW_rnk.o
obj-$(CONFIG_TRACE) += SEGGER_SYSVIEW_Config_rnk.o
obj-$(CONFIG_TRACE) += SEGGER_RTT.o
obj-$(CONFIG_TRACE) += SEGGER_RTT_printf.o
